// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEOY9XrJj_tWqX3KH_p23I9M6D6qfVDn8',
    appId: '1:145358866222:web:dd96827525b282f851dcbf',
    messagingSenderId: '145358866222',
    projectId: 'rick-and-morty-7b22e',
    authDomain: 'rick-and-morty-7b22e.firebaseapp.com',
    storageBucket: 'rick-and-morty-7b22e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPIIKZraZVUq9kv8Ov62Y_feDY05JHlQ',
    appId: '1:145358866222:android:3b62ad11723c246c51dcbf',
    messagingSenderId: '145358866222',
    projectId: 'rick-and-morty-7b22e',
    storageBucket: 'rick-and-morty-7b22e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAPxaMzTeTuucqHUy2qky5j6cujQVwBM',
    appId: '1:145358866222:ios:9aaec20ba17b491b51dcbf',
    messagingSenderId: '145358866222',
    projectId: 'rick-and-morty-7b22e',
    storageBucket: 'rick-and-morty-7b22e.appspot.com',
    iosBundleId: 'com.example.rickAndMorty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgAPxaMzTeTuucqHUy2qky5j6cujQVwBM',
    appId: '1:145358866222:ios:d6939c976119d30751dcbf',
    messagingSenderId: '145358866222',
    projectId: 'rick-and-morty-7b22e',
    storageBucket: 'rick-and-morty-7b22e.appspot.com',
    iosBundleId: 'com.example.rickAndMorty.RunnerTests',
  );
}
